name: Rajiv Hemanth
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
